# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('text', models.TextField()),
                ('user_created', models.IntegerField()),
                ('time_created', models.DateTimeField()),
                ('user_modified', models.IntegerField()),
                ('time_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_note',
            },
        ),
    ]
